### ISSUE TITLE
Whistle00.fbx does not load and is broken

### ISSUE THREAD

**Issue by KAUTARUMA** [zviznemte/PikminBloomAssets#3]
![image](https://user-images.githubusercontent.com/75647306/147847334-d1ea4d62-6ddc-4054-a9bc-ed9406dab9f5.png)
![image](https://user-images.githubusercontent.com/75647306/147847336-92ea30d8-6dc9-4597-9768-145d9a822d9a.png)

**Comment by zviznemte** [comment]
In FBX Viewer is not in the center of the screen, search in left bottom corner, there is the whistle, same for some other models. Let me know if you find
